### ISSUE TITLE
몇가지 영어에선 감지가 안되네요

### ISSUE THREAD

**Issue by popop098** [Seol7523/KoreanWordDetection#8]
`존나`는 존재하나 영어로 했을때 `whssk`는 감지가 안됩니다.

실사용하며 감지가 안되는 부분은 계속해서 이슈수정 또는 코멘트 달겠습니다.

**Comment by Seol7523** [comment]
확인해보겠습니다 감사합니다

**Comment by seolmango** [comment]
> `존나`는 존재하나 영어로 했을때 `whssk`는 감지가 안됩니다.
> 
> 실사용하며 감지가 안되는 부분은 계속해서 이슈수정 또는 코멘트 달겠습니다.

확인해보니 중복문자열을 제거하는 알고리즘에서 whssk ==> whsk
로 변경되어 감지가 어려운것으로 보입니다.

해당 문제에 대해서는 개선방안을 찾아보겠습니다

**Comment by popop098** [comment]
`준다` 가 욕설도 아니고 db에도 없는데 감지되네요.. 이 부분도 확인이 필요해보입니다

**Comment by seolmango** [comment]
> `준다` 가 욕설도 아니고 db에도 없는데 감지되네요.. 이 부분도 확인이 필요해보입니다

그건 머신러닝을 사용하지 않는 이 모듈의 고질적인 문제입니다. 단순히 비교하는 방식의 알고리즘이다보니 '준다'라는 말의 의미를 파악하지 못해요.... 확인해보니 '찐따'와 유사하여 감지했다고 하네요. 이 문제도 해결하기위한 방법을 고안해야할것같습니다. 

계속 제보해주셔서 감사합니다. 빠른 시일내에 고쳐볼게요..
